Feature/create pages
kuanyshtokanov/startupjs_shop pull request #1
Opened 2021-01-20 12:42 UTC by kuanyshtokanov

2021-02-09 13:21 UTC, ssstelsss commented
![image](https://user-images.githubusercontent.com/58818714/107369442-dac67080-6af2-11eb-8724-c4fb4bce1408.png)

2021-02-11 12:45 UTC, ssstelsss requested changes

2021-02-11 12:45 UTC, ssstelsss commented on components/Breadcrumb/index.js
> +    ImageBackground(source={uri: base+'/assets/breadcrumb.jpg'} style=styles.backgroundContainer)
BASE_URL+'/assets. Какой смысл создавать переменную base?

2021-02-11 12:51 UTC, ssstelsss commented
на макете
![image](https://user-images.githubusercontent.com/58818714/107638665-f1023700-6c80-11eb-8975-c90fd39bf561.png)
у тебя 
![image](https://user-images.githubusercontent.com/58818714/107638703-fcedf900-6c80-11eb-95be-3f8c617837c2.png)

2021-02-12 09:35 UTC, ssstelsss requested changes

2021-02-12 09:35 UTC, ssstelsss commented on components/Breadcrumb/index.styl
> +  padding-bottom 9u
давай заменим на padding 9u 0

2021-02-12 09:35 UTC, ssstelsss commented on components/Breadcrumb/index.styl
> +  padding-bottom 9u
ну и дальше по проекту посмотри

2021-02-12 09:35 UTC, ssstelsss commented on components/Button/index.js
> +      View.btn(styleName=[{ info, action }])
styleName={ info, action }, тут не нужен массив

2021-02-12 09:35 UTC, ssstelsss commented on components/Button/index.js
> +      View.btn(styleName=[{ info, action }])
везде посмотри

2021-02-12 09:35 UTC, ssstelsss commented on components/Button/index.styl
> +  // border-radius 1u
коменты убери везде

2021-02-12 09:35 UTC, ssstelsss commented on components/Button/index.styl
> +  border: 1px solid #dddddd
: лишние, посмотри везде

2021-02-12 09:35 UTC, ssstelsss commented on components/Button/index.styl
> +  &.action, &.info
точно нужно два одинаковых модификатора, одним не обойдемся?

2021-02-12 09:35 UTC, ssstelsss commented on components/Footer/index.styl
> +  margin-right auto
margin-right и margin-buttom мы не используем без особой нужды. https://core.dmapper.co/docs/css-guide прочти внимательно и примени все, что там написано относительно своего проекта

2021-02-12 09:35 UTC, ssstelsss commented on components/Header/Menu/index.js
> +  const base = BASE_URL
не используется

2021-02-12 09:35 UTC, ssstelsss commented on components/Header/index.js
> +  const base = BASE_URL
тоже не используется, посмотри по всему проекту чтобы не было неиспользуемых переменных

2021-02-12 09:35 UTC, ssstelsss commented on components/MenuItem/index.js
> +    View.menuItem(styleName=[{last:last}])
styleName={last}

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Colors/ColorItems/index.js
> +      View.color.red
давай создадим массив с цветами, а здесь пройдем по массиву

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Filter/index.styl
> +  flex-basis 99%
99% как правило плохое решение

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Products/ProductsBar/Filter/index.js
> +        FontAwesomeIcon.icon(icon=gridIcon size=20 color=(!listView ? '#ff4136' : '#6c6c6c'))
старайся избегать отрицаний где это возможно
listView ? '#6c6c6c' : '#ff4136'

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Products/ProductsContent/Grid/GridItem/index.styl
> +  padding 0 1.5u
дробные падинги, как правило, плохая идея

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Products/ProductsContent/List/ListItem/WishList/index.js
> +  const [isFavorite, addToFavorite] = useState(false)
isFavorite, setIsFavorite
посмотри правила именования геттеро и сетторов хуков

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Products/ProductsContent/List/ListItem/WishList/index.js
> +  const uri = `/main/favorite${isFavorite ? '-selected' : ''}.png`
не используется

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Products/ProductsContent/List/ListItem/WishList/index.styl
> +  stroke: black;
думаю вполне можно обойтись без stroke

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Products/ProductsContent/List/ListItem/index.js
> +import Button from '../../../../../Button'
import Button from 'components/Button'

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Products/ProductsContent/List/ListItem/index.js
> +import Button from '../../../../../Button'
посмотри везде

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Products/ProductsContent/List/ListItem/index.styl
> +    width 320px
40u

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Products/ProductsContent/index.js
> +  const products = [
давай это вынесем в константы

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Products/ProductsContent/index.styl
> +    flex-flow row wrap
кажется таблет ничем не отличается от мобайла

2021-02-12 09:35 UTC, ssstelsss commented on components/ShopPage/Sizes/index.js
> +        Text.size="xl"
тоже давай сделаем массив и потом пройдем по нему

2021-02-12 09:35 UTC, ssstelsss commented on components/Stars/index.js
> +  const ratings = [1, 2, 3, 4, 5]
new Array(5).fill(1)

2021-02-12 09:35 UTC, ssstelsss commented on main/pages/PHome/index.js
> +import Header from '../../../components/Header'
same

2021-02-17 11:13 UTC, ssstelsss commented on components/ShopPage/Colors/index.js
> +            last=index===colors.length-1
давай просто передавать колор и там его просто в стайл кидать

2021-02-17 11:14 UTC, ssstelsss commented
посмотри внимательно все комментарии, много просто пропущены. Если не согласен, то отвечай прям в коментах чтобы было видно, что ты увидел комент.

2021-02-17 12:06 UTC, kuanyshtokanov commented on components/ShopPage/Colors/index.js
> +            last=index===colors.length-1
пробовал так. почему-то не работает

2021-04-28 13:22 UTC, merged